<?php
defined( 'ABSPATH' ) || exit;

return [
	'categories' => [
		'Digital Adoption',
		'Product',
		'Enterprise',
		'Training',
	],
	'tags' => [
		'onboarding',
		'UX',
		'analytics',
		'automation',
		'training',
		'productivity',
		'enterprise',
	],
	'posts' => [
		[
			'title'      => 'Getting Started with Digital Adoption',
			'excerpt'    => 'Digital adoption is the process of learning to use technology to its full potential. Discover how to accelerate your organization\'s digital transformation journey.',
			'content'    => '<p>Digital adoption is no longer optional — it\'s a competitive necessity. Organizations that successfully adopt new technologies see measurable gains in productivity, employee satisfaction, and customer outcomes.</p><p>In this guide, we explore the core principles of digital adoption and how to build a strategy that works for your organization.</p>',
			'image_seed' => 'digital-adoption',
			'categories' => [ 'Digital Adoption' ],
			'tags'       => [ 'onboarding', 'UX' ],
		],
		[
			'title'      => 'How to Improve Employee Onboarding with Digital Tools',
			'excerpt'    => 'Employee onboarding sets the tone for the entire employment experience. Learn how digital adoption platforms can transform your onboarding process from day one.',
			'content'    => '<p>The first 90 days of an employee\'s journey have a disproportionate impact on long-term retention. A well-structured digital onboarding program reduces time-to-productivity and improves engagement.</p>',
			'image_seed' => 'employee-onboarding',
			'categories' => [ 'Digital Adoption', 'Training' ],
			'tags'       => [ 'onboarding', 'training', 'productivity' ],
		],
		[
			'title'      => 'Measuring ROI of Your Digital Adoption Platform',
			'excerpt'    => 'Understanding the return on investment from your digital adoption platform is crucial for continued buy-in. Here\'s how to measure success effectively and present results.',
			'content'    => '<p>ROI measurement for digital adoption platforms requires looking beyond traditional metrics. Consider time savings, error reduction, support ticket deflection, and employee confidence scores alongside hard revenue numbers.</p>',
			'image_seed' => 'roi-analytics',
			'categories' => [ 'Product', 'Enterprise' ],
			'tags'       => [ 'analytics', 'enterprise' ],
		],
		[
			'title'      => 'Top 5 UX Trends Shaping Enterprise Software in 2025',
			'excerpt'    => 'Enterprise software UX is evolving rapidly. Stay ahead of the curve with these key trends that are reshaping how employees interact with business applications.',
			'content'    => '<p>From contextual AI assistance to zero-UI interfaces, enterprise software is undergoing a design revolution. The tools that will win in 2025 are those that meet users where they are, not where the product team assumed they\'d be.</p>',
			'image_seed' => 'ux-trends',
			'categories' => [ 'Product' ],
			'tags'       => [ 'UX', 'enterprise', 'productivity' ],
		],
		[
			'title'      => 'Automating Repetitive Tasks with Digital Workflows',
			'excerpt'    => 'Automation is the key to scalability. Discover how digital workflows can eliminate repetitive manual tasks and free your team to focus on high-value work.',
			'content'    => '<p>The average knowledge worker spends over 3 hours per day on tasks that could be partially or fully automated. Digital workflow automation tools are making it possible to reclaim that time without complex engineering work.</p>',
			'image_seed' => 'automation-workflow',
			'categories' => [ 'Enterprise' ],
			'tags'       => [ 'automation', 'productivity' ],
		],
		[
			'title'      => 'Building a Culture of Continuous Learning',
			'excerpt'    => 'Continuous learning is essential in today\'s fast-changing workplace. Learn how to create a learning culture that drives growth, innovation, and long-term employee retention.',
			'content'    => '<p>Organizations that invest in continuous learning consistently outperform their peers. But learning culture isn\'t built through mandatory training sessions — it requires embedding learning into the daily flow of work.</p>',
			'image_seed' => 'continuous-learning',
			'categories' => [ 'Training', 'Digital Adoption' ],
			'tags'       => [ 'training', 'onboarding' ],
		],
		[
			'title'      => 'The Future of CRM: AI-Powered Digital Adoption',
			'excerpt'    => 'CRM platforms are becoming smarter with AI. Explore how AI-powered digital adoption tools are transforming customer relationship management and sales productivity.',
			'content'    => '<p>AI is changing CRM from a record-keeping system into an active sales partner. Combined with digital adoption overlays, reps now get real-time guidance without ever leaving the interface they\'re working in.</p>',
			'image_seed' => 'crm-future',
			'categories' => [ 'Product', 'Enterprise' ],
			'tags'       => [ 'automation', 'analytics', 'enterprise' ],
		],
		[
			'title'      => 'User Analytics: Understanding How Employees Use Software',
			'excerpt'    => 'Data-driven insights into software usage patterns can help you optimize processes and identify training gaps before they become costly problems.',
			'content'    => '<p>Usage analytics reveal the gap between how software was designed to be used and how it\'s actually being used. Bridging that gap is often the highest-leverage activity for improving productivity and reducing errors.</p>',
			'image_seed' => 'user-analytics',
			'categories' => [ 'Product' ],
			'tags'       => [ 'analytics', 'UX', 'productivity' ],
		],
		[
			'title'      => 'Enterprise Change Management Best Practices',
			'excerpt'    => 'Managing organizational change is one of the biggest challenges for enterprise leaders. These proven best practices will help you navigate transformation with confidence.',
			'content'    => '<p>Change management succeeds when it treats the human element as the primary variable, not an afterthought. Communication cadence, leadership alignment, and early-adopter programs are the three pillars of effective change at scale.</p>',
			'image_seed' => 'change-management',
			'categories' => [ 'Enterprise', 'Training' ],
			'tags'       => [ 'enterprise', 'training', 'onboarding' ],
		],
		[
			'title'      => 'Scaling Training Programs Across Global Teams',
			'excerpt'    => 'Training a distributed global workforce requires a strategic approach. Discover how digital adoption platforms enable scalable, consistent training across geographies and time zones.',
			'content'    => '<p>Global teams face a unique training challenge: consistency across cultures, languages, and time zones. Digital adoption platforms solve this by delivering contextual guidance in the flow of work, regardless of where the employee is located.</p>',
			'image_seed' => 'global-training',
			'categories' => [ 'Training' ],
			'tags'       => [ 'training', 'automation', 'productivity' ],
		],
		[
			'title'      => 'Reducing Software Abandonment with In-App Guidance',
			'excerpt'    => 'Software abandonment costs businesses millions each year. In-app guidance provides contextual help exactly when users need it, dramatically boosting long-term adoption rates.',
			'content'    => '<p>Software abandonment happens when the friction of learning exceeds the perceived value of the tool. In-app guidance reduces that friction at the moment it matters most — when the user is stuck and considering giving up.</p>',
			'image_seed' => 'in-app-guidance',
			'categories' => [ 'Digital Adoption', 'Product' ],
			'tags'       => [ 'UX', 'onboarding', 'analytics' ],
		],
	],
];
